### ISSUE TITLE
Error webservice.xml

### ISSUE THREAD

**Issue by martinpfeiferdev** [tuscanicz/BeSimpleSoap#11]
The class Classmap in SoapServer not exists, please remove this parameter: `<parameter key="besimple.soap.server.classmap.class">BeSimple\SoapServer\Classmap</parameter>`

Service: `<service id="besimple.soap.server.classmap" class="%besimple.soap.server.classmap.class%" public="false" />`

`<argument type="service" id="besimple.soap.server.classmap" />`

**Comment by tuscanicz** [comment]
Hi,

I am sorry but the BeSimpleSoapBundle is currently not supported in this fork. I am using Symfony Framework in all of my projects but the bundle seems to be too robust. I would not recommend you to use it. If you're somehow using it, feel free to send me a pull request with you improvements.

This is also mentioned in readme 😄  

> Unsupported! ... Will not work since the Symfony libraries were removed and usages of other components were not refactored. Feel free to fork this repository and fix it!

Thank you!
