### ISSUE TITLE
_getLastResponse deprecated

### ISSUE THREAD

**Issue by sanchobouillant** [tuscanicz/BeSimpleSoap#12]
Hi,

I want to use getLastResponse but it's deprecated. How can i get the last response and last request ?

Do you have any code example ?

Thanks

**Comment by tuscanicz** [comment]
Hi!

You can get a clue in tests dir here:
https://github.com/tuscanicz/BeSimpleSoap/blob/master/tests/BeSimple/SoapClient/SoapClientTest.php

For example, see the `SoapClientTest::testSoapCallWithCustomEndpointValid` test method, here you get the data from `$soapResponse->getTracingData()`

You have to build SoapClient with tracing data, as you can see in the test case:

_SoapClientOptionsBuilder::create**WithTracing**()_

Did it help you? The difference is that these tracing data are immutable. The original native SoapClient methods were holding a state of one of the previous calls which is not the package design you'd like to use.

Petr

**Comment by sanchobouillant** [comment]
That's perfect. Thanks :)
